---
title: "TestShinyRmd"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE} 
library("flexdashboard") #No incluir el codigo
library("shiny")
```

Pagina 1 {data-icon="fa-signal"} 
==================================================


Column {data-width=650}
--------------------------------------------------

### Chart A

Ejemplo de grafica

```{r}
data <- mtcars
boxplot(data$mpg, col = "orange")
```

Column {data-width=350}
--------------------------------------------------

# Pagina 2

## Columna 1

### Tablas

```{r}
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2)
)

#Importar contenido interactivo en el markdown

renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser eruption duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
# instll.packages("shiny") - Para empezar a crear archivos shiny
```

